/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kartustock;

import com.barang.BarangKontrol;
import com.barang.TabelModelBarang;
import com.barang.barang;
import com.barang.daftarmenuArsip;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author rai
 */
public class FrameCetak extends javax.swing.JFrame {

    /**
     * Creates new form FrameCetak
     */
    public FrameCetak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKartuStock = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jInternalFramejCheckBox = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jInternalFramejDateChooserAwal = new com.toedter.calendar.JDateChooser();
        jInternalFramejDateChooserAkhir = new com.toedter.calendar.JDateChooser();
        jInternalFramejButtonTampil = new javax.swing.JButton();
        jInternalFramejButtonCetak = new javax.swing.JButton();
        jInternalFrameKeluar = new javax.swing.JButton();
        jInternalFramejTextField = new javax.swing.JTextField();
        jInternalFramejButtonLihatKodeBarang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Frame Cetak Kartu Stock");
        setBackground(new java.awt.Color(59, 142, 172));

        jPanel9.setBackground(new java.awt.Color(59, 142, 172));

        jScrollPane1.setBackground(new java.awt.Color(240, 242, 242));

        jTableKartuStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "No. Bukti", "Keterangan", "Masuk", "Keluar", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableKartuStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableKartuStockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableKartuStock);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(59, 142, 172));

        jLabel18.setText("s/d");

        jInternalFramejCheckBox.setText("pilih semua");
        jInternalFramejCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInternalFramejCheckBoxMouseClicked(evt);
            }
        });

        jLabel12.setText("Pilih Kode Barang");

        jLabel13.setText("Tanggal");

        jInternalFramejButtonTampil.setText("Tampil");
        jInternalFramejButtonTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInternalFramejButtonTampilActionPerformed(evt);
            }
        });

        jInternalFramejButtonCetak.setText("Cetak");
        jInternalFramejButtonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInternalFramejButtonCetakActionPerformed(evt);
            }
        });

        jInternalFrameKeluar.setText("Keluar");
        jInternalFrameKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInternalFrameKeluarActionPerformed(evt);
            }
        });

        jInternalFramejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInternalFramejTextFieldActionPerformed(evt);
            }
        });

        jInternalFramejButtonLihatKodeBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kartustock/logviewer.png"))); // NOI18N
        jInternalFramejButtonLihatKodeBarang.setToolTipText("Tombil search");
        jInternalFramejButtonLihatKodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInternalFramejButtonLihatKodeBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jInternalFramejDateChooserAwal, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(jInternalFramejTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jInternalFramejDateChooserAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jInternalFramejButtonLihatKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jInternalFramejButtonTampil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jInternalFramejButtonCetak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jInternalFrameKeluar))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jInternalFramejCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jInternalFramejButtonTampil)
                        .addComponent(jInternalFramejButtonCetak)
                        .addComponent(jInternalFrameKeluar)
                        .addComponent(jLabel12)
                        .addComponent(jInternalFramejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jInternalFramejButtonLihatKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFramejDateChooserAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInternalFramejDateChooserAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInternalFramejCheckBox)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jInternalFramejCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInternalFramejCheckBoxMouseClicked
        if (jInternalFramejCheckBox.isSelected()) {
            jInternalFramejDateChooserAwal.setDateFormatString(null);
            jInternalFramejDateChooserAkhir.setDateFormatString(null);
        }
    }//GEN-LAST:event_jInternalFramejCheckBoxMouseClicked

    private void jInternalFramejButtonTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInternalFramejButtonTampilActionPerformed
        String selected = jInternalFramejTextField.getText();
//        barang b=new barang();
//        b.setKodeBarang(selected);
//        KartuStock k=new KartuStock();
//                k.setKodeBarang(b);
        if (jInternalFramejCheckBox.isSelected()) {
            try {
                List<KartuStock> daftarStock = KartuStockKontrol.getKoneksi().LihatKartuStock(selected);
                KartuStockTableModel model = new KartuStockTableModel(daftarStock);
                model.fireTableDataChanged();
                jTableKartuStock.setModel(model);
            } catch (SQLException ex) {
                Logger.getLogger(FormKartuStock.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            //            String kolomAwal = jTextFieldAwalCetakFrame.getText();
            //            String kolomAkhir = jTextFieldAkhirCetakFrame.getText();
            //            try {
            //                List<barang> listKategori = BarangKontrol.getKoneksi().TampilTabelCetak(kolomAwal, kolomAkhir);
            //                TabelModelBarang model = new TabelModelBarang(listKategori);
            //                model.fireTableDataChanged();
            //                jTableJInternalFrameCetakBarang.setModel(model);
            //            }
            //            catch (SQLException ex) {
            //                Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
            //            }
        }
    }//GEN-LAST:event_jInternalFramejButtonTampilActionPerformed

    private void jInternalFramejButtonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInternalFramejButtonCetakActionPerformed
        Connection kon = null;
        kon = new com.koneksi.koneksi().getkoneksi2();
        String reportSource = "";

        //        String kowal = jTextFieldAwalCetakFrame.getText();
        //        String kohir = jTextFieldAkhirCetakFrame.getText();
        if (jInternalFramejCheckBox.isSelected()) {
            reportSource = "./src/com/barang/DaftarMenuArsip.jasper";
        } else {

            reportSource = "./laporan/LaporanCetakBarangdenganParameter.jasper";
        }
        Map<String, Object> params = new HashMap<String, Object>();
        //        params.put("kodeawal", kowal);
        //        params.put("kodeakhir", kohir);
        try {
            JasperPrint jasperPrint = JasperFillManager.fillReport(reportSource, params, kon);
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jInternalFramejButtonCetakActionPerformed

    private void jInternalFrameKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInternalFrameKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jInternalFrameKeluarActionPerformed

    private void jInternalFramejButtonLihatKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInternalFramejButtonLihatKodeBarangActionPerformed
        FrameKodeBarang f = new FrameKodeBarang();
        f.setVisible(true);
    }//GEN-LAST:event_jInternalFramejButtonLihatKodeBarangActionPerformed

    private void jInternalFramejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInternalFramejTextFieldActionPerformed
        String kode = jInternalFramejTextField.getText();
        barang kb = new barang();
        kb.setKodeBarang(kode);
//        try {
//            String namaBarang = KartuStockKontrol.getKoneksi().cariNamaBarang(kb);
//            String kategori = KartuStockKontrol.getKoneksi().cariKategori(kb);
//            String satuan = KartuStockKontrol.getKoneksi().cariSatuan(kb);
//
//            jTextFieldNamaBarang.setText(namaBarang);
//            jTextFieldKategori.setText(kategori);
//            jTextFieldSatuan.setText(satuan);
//            if (jTextFieldNamaBarang.getText().equals("")) {
//                jInternalFrameKodeBarang.setVisible(true);
        JOptionPane.showMessageDialog(rootPane, "Kode barang tidak terdapat dalam database, silahkan menekan icon search");

//            }
//            ListStock();        
    }//GEN-LAST:event_jInternalFramejTextFieldActionPerformed

    private void jTableKartuStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKartuStockMouseClicked
//        int baris = jTableKartuStock.getSelectedRow();
//        String noBukti, tanggal, keterangan, masuk, keluar;
//        tanggal = jTableKartuStock.getValueAt(baris, 0).toString();
//        noBukti = jTableKartuStock.getValueAt(baris, 1).toString();
//        keterangan = jTableKartuStock.getValueAt(baris, 2).toString();
//        masuk = jTableKartuStock.getValueAt(baris, 3).toString();
//        keluar = jTableKartuStock.getValueAt(baris, 4).toString();
//
//        String tgl1 = tanggal.substring(0, 10);
//        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//
//        try {
//            Date tgl2 = sdf.parse(tgl1);
//
//            SimpleDateFormat sdf2 = new SimpleDateFormat("dd MMM yy");
//
//            String tgl3 = sdf2.format(tgl2);
//
//            Date tgl4 = sdf2.parse(tgl3);
//            jDateChooserCalender.setDate(tgl4);
//        } catch (ParseException ex) {
//        }

//        jTextFieldNoBukti.setText(noBukti);
//        jTextFieldKeterangan.setText(keterangan);
//        jTextFieldMasuk.setText(masuk);
//        jTextFieldKeluar.setText(keluar);
//        jButtonSimpan.setText("Update");
        //        if (jButtonBatal.isSelected()) {
        //            ListStockKosong();
        //        }
    }//GEN-LAST:event_jTableKartuStockMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCetak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jInternalFrameKeluar;
    private javax.swing.JButton jInternalFramejButtonCetak;
    private javax.swing.JButton jInternalFramejButtonLihatKodeBarang;
    private javax.swing.JButton jInternalFramejButtonTampil;
    private javax.swing.JCheckBox jInternalFramejCheckBox;
    private com.toedter.calendar.JDateChooser jInternalFramejDateChooserAkhir;
    private com.toedter.calendar.JDateChooser jInternalFramejDateChooserAwal;
    private javax.swing.JTextField jInternalFramejTextField;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKartuStock;
    // End of variables declaration//GEN-END:variables
}
