package com.kategori.barang;

import com.koneksi.koneksi;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author raikeiji
 */
public class KategoriBarangForm2 extends javax.swing.JFrame {

    private int kesalahan;

    public KategoriBarangForm2() {
        initComponents();
        lihatkategori();
        tampilanAwalTeksKodeKategori();
        tampilanAwalTeksNamaKategori();
        jButtonBatal.setEnabled(false);
        jButtonHapus.setEnabled(false);
        jButtonSimpan.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelKodeKategori = new javax.swing.JLabel();
        jLabelNamaKategori = new javax.swing.JLabel();
        jTextFieldKodeKategori = new javax.swing.JTextField();
        jTextFieldNamaKategori = new javax.swing.JTextField();
        jLabelErrorKode = new javax.swing.JLabel();
        jLabelErrorNama = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonSimpan = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();
        jButtonKeluar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKategori = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("KATEGORI BARANG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBounds(0, 0, 530, 70);
        jDesktopPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabelKodeKategori.setText("KODE KATEGORI");

        jLabelNamaKategori.setText("NAMA KATEGORI");

        jTextFieldKodeKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldKodeKategoriMouseClicked(evt);
            }
        });
        jTextFieldKodeKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKodeKategoriActionPerformed(evt);
            }
        });

        jTextFieldNamaKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNamaKategoriMouseClicked(evt);
            }
        });

        jLabelErrorKode.setForeground(new java.awt.Color(255, 0, 51));

        jLabelErrorNama.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelKodeKategori)
                    .addComponent(jLabelNamaKategori))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldKodeKategori, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(jTextFieldNamaKategori)
                    .addComponent(jLabelErrorNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelErrorKode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKodeKategori)
                    .addComponent(jTextFieldKodeKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelNamaKategori))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelErrorKode, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNamaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelErrorNama, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jPanel2.setBounds(0, 70, 530, 120);
        jDesktopPane1.add(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonSimpan.setText("SIMPAN");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jButtonHapus.setText("HAPUS");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonBatal.setText("BATAL");
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });

        jButtonKeluar.setText("KELUAR");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(jButtonKeluar)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSimpan)
                    .addComponent(jButtonHapus)
                    .addComponent(jButtonBatal)
                    .addComponent(jButtonKeluar))
                .addGap(344, 344, 344))
        );

        jPanel3.setBounds(0, 190, 530, 50);
        jDesktopPane1.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Table Kategori", 0, 0, new java.awt.Font("Times New Roman", 2, 10), java.awt.Color.gray)); // NOI18N

        jTableKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "KODE KATEGORI", "NAMA KATEGORI"
            }
        ));
        jTableKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableKategoriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableKategori);
        jTableKategori.getColumnModel().getColumn(1).setResizable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBounds(0, 240, 530, 170);
        jDesktopPane1.add(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        jTextFieldKodeKategori.setText("");
        jTextFieldNamaKategori.setText("");
        jButtonBatal.setEnabled(false);
        jButtonHapus.setEnabled(false);
        jButtonSimpan.setEnabled(false);
        jButtonSimpan.setText("SIMPAN");
        jLabelErrorKode.setText("");
        jLabelErrorNama.setText("");
        tampilanAwalTeksKodeKategori();
        tampilanAwalTeksNamaKategori();
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        kategoribarang kb = new kategoribarang();
//        kategoribarangkontrol kbk = new kategoribarangkontrol(koneksi.getkoneksi());
        kategoribarangkontrol kbk = new kategoribarangkontrol(com.koneksi.koneksi.getkoneksi("hr", "hr", "jdbc:Oracle:thin:@localhost:1521:xe"));
        try {
            kesalahan = 2;
            if (kesalahan != 0) {
                kesalahanID();
                kesalahanNama();
                if (kesalahan == 0) {
                    kb.setKode_kategori(jTextFieldKodeKategori.getText());
                    kb.setNama_kategori(jTextFieldNamaKategori.getText());
                    kbk.tambahKategoriprepare2(kb);
                    JOptionPane.showMessageDialog(rootPane, "Kode Kategori"
                            + jTextFieldKodeKategori.getText() + ", Nama Kategori "
                            + jTextFieldNamaKategori.getText() + " telah di masukkan ke database");
                }
            }
        } catch (Exception ex) {
        }
        tampilanAwalTeksKodeKategori();
        tampilanAwalTeksNamaKategori();
        lihatkategori();
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        String kodekategori = jTextFieldKodeKategori.getText();
        String namakategori = jTextFieldNamaKategori.getText();
        kategoribarang kd = new kategoribarang();
        kd.setKode_kategori(kodekategori);
        kd.setNama_kategori(namakategori);
//        kategoribarangkontrol kbk = new kategoribarangkontrol(koneksi.getkoneksi());
        kategoribarangkontrol kbk = new kategoribarangkontrol(com.koneksi.koneksi.getkoneksi("hr", "hr", "jdbc:Oracle:thin:@localhost:1521:xe"));
        try {
            kbk.deleteKategoriprepare(kd);
        } catch (Exception ex) {
            Logger.getLogger(kategoribarangform.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(rootPane, "Kode kategori" + kodekategori + ", nama kategori" + namakategori + " telah di hapus ke database");
//        jTextFieldKodeKategori.setText("");
//        jTextFieldNamaKategori.setText("");
        tampilanAwalTeksKodeKategori();
        tampilanAwalTeksNamaKategori();
        lihatkategori();
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jTextFieldKodeKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKodeKategoriActionPerformed
        String kode = jTextFieldKodeKategori.getText();
        kategoribarang kb = new kategoribarang();
        kb.setKode_kategori(kode);
        if (kode.equals("") || kode == null) {
            JOptionPane.showMessageDialog(rootPane, "Kode harus diisi");
        } else {
            try {
//                kategoribarangkontrol kbk = new kategoribarangkontrol(koneksi.getkoneksi());
                kategoribarangkontrol kbk = new kategoribarangkontrol(com.koneksi.koneksi.getkoneksi("hr", "hr", "jdbc:Oracle:thin:@localhost:1521:xe"));
                String namakategori = kbk.getKoneksiKategori().carikategoribarang(kb);
                jTextFieldNamaKategori.setEnabled(true);
                jTextFieldNamaKategori.setText(namakategori);
                jTextFieldNamaKategori.setForeground(Color.BLACK);
                repaint();
                revalidate();
                if (jTextFieldNamaKategori.getText().isEmpty()) {
                    jButtonSimpan.setText("SIMPAN");
                } else {
                    jButtonSimpan.setText("UPDATE");
                }
            } catch (Exception e) {
                jTextFieldNamaKategori.setText("");
                jTextFieldNamaKategori.requestFocus();
            }
        }
    }//GEN-LAST:event_jTextFieldKodeKategoriActionPerformed

    private void jTableKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKategoriMouseClicked
        int baris = jTableKategori.getSelectedRow();

        String kode = jTableKategori.getValueAt(baris, 0).toString();
        String nama = jTableKategori.getValueAt(baris, 1).toString();

        jButtonBatal.setEnabled(true);
        jButtonSimpan.setEnabled(true);
        jButtonHapus.setEnabled(true);
        jButtonSimpan.setText("UPDATE");

        jTextFieldKodeKategori.setEnabled(true);
        jTextFieldNamaKategori.setEnabled(true);

        jTextFieldKodeKategori.setForeground(Color.BLACK);
        jTextFieldNamaKategori.setForeground(Color.BLACK);

        jTextFieldKodeKategori.setText(kode);
        jTextFieldNamaKategori.setText(nama);

    }//GEN-LAST:event_jTableKategoriMouseClicked

    private void jTextFieldKodeKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldKodeKategoriMouseClicked
        jButtonSimpan.setEnabled(true);
        jButtonHapus.setEnabled(true);
        jButtonBatal.setEnabled(true);
        jButtonKeluar.setEnabled(true);

        String kodekategori = jTextFieldKodeKategori.getText();
        String namakategori = jTextFieldNamaKategori.getText();

        kategoribarang kd = new kategoribarang();

        kd.setKode_kategori(kodekategori);
        kd.setNama_kategori(namakategori);

//        kategoribarangkontrol kbk = new kategoribarangkontrol(com.koneksi.koneksi.getkoneksi());
        kategoribarangkontrol kbk = new kategoribarangkontrol(com.koneksi.koneksi.getkoneksi("hr", "hr", "jdbc:Oracle:thin:@localhost:1521:xe"));

        if (jTextFieldKodeKategori.getText().equals("Masukkan Kode Kategori") || !jTextFieldKodeKategori.getText().equals("")
                || jTextFieldKodeKategori.getText().equals("")) {
            jTextFieldKodeKategori.setText("");
            jTextFieldKodeKategori.setForeground(Color.BLACK);
            repaint();
            revalidate();
            jLabelErrorNama.setText("");
            jLabelErrorKode.setText("");
        }
    }//GEN-LAST:event_jTextFieldKodeKategoriMouseClicked

    private void jTextFieldNamaKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNamaKategoriMouseClicked
        if (jTextFieldNamaKategori.getText().equals("") || jTextFieldNamaKategori.getText().equals("Masukkan Nama Kategori")) {
            jButtonSimpan.setText("SIMPAN");
            jLabelErrorNama.setEnabled(true);
            jLabelErrorNama.setText("masukkan kode kategori terlebih dahulu");
            jButtonBatal.setEnabled(false);
            jButtonHapus.setEnabled(false);
            jButtonKeluar.setEnabled(true);
            jButtonSimpan.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldNamaKategoriMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KategoriBarangForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KategoriBarangForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KategoriBarangForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KategoriBarangForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new KategoriBarangForm2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelErrorKode;
    private javax.swing.JLabel jLabelErrorNama;
    private javax.swing.JLabel jLabelKodeKategori;
    private javax.swing.JLabel jLabelNamaKategori;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKategori;
    private javax.swing.JTextField jTextFieldKodeKategori;
    private javax.swing.JTextField jTextFieldNamaKategori;
    // End of variables declaration//GEN-END:variables

    GridBagConstraints cons = new GridBagConstraints();
    private String noID, nam;

    public String getID() {
        return noID;
    }

    public String getNama() {
        return nam;
    }

    public void setID(String id) throws IDException {
        String pola = "[0-9]*";
        if (id.matches(pola)) {
            this.noID = id;
        } //        else if (id.equalsIgnoreCase("") || id.equalsIgnoreCase("Masukkan Nomor Identitas")) {
        //            throw new IDException("harus di isi");
        //        } 
        else {
            throw new IDException("hanya masukkan angka");
        }
    }

    public void setNama(String nama) throws NamaException {
        String pola = "[a-zA-Z ]*";
        if (nama.matches(pola)) {
            this.nam = nama;
        } else if (nama.equalsIgnoreCase("") || nama.equalsIgnoreCase("Masukkan Nama Kategori")) {
            throw new NamaException("harus di isi");
        } else {
            throw new NamaException("tidak boleh ada angka");
        }
    }

    private void lihatkategori() {
        try {
            List<kategoribarang> listkat = kategoribarangkontrol.getKoneksiKategori().lihatSeluruhKateogri();
            KategoriTableModel katmodel = new KategoriTableModel(listkat);
            jTableKategori.setModel(katmodel);
        } catch (Exception e) {
        }
    }

    public void tampilanAwalTeksKodeKategori() {
        jTextFieldKodeKategori.setText("Masukkan Kode Kategori");
        jTextFieldKodeKategori.setPreferredSize(jTextFieldKodeKategori.getPreferredSize());
//        teks_kode_kategori.setMaximumSize(teks_kode_kategori.getPreferredSize());
        jTextFieldKodeKategori.setForeground(Color.LIGHT_GRAY);
    }

    public void tampilanAwalTeksNamaKategori() {
        jTextFieldNamaKategori.setText("Masukkan Nama Kategori");
        jTextFieldNamaKategori.setPreferredSize(jTextFieldNamaKategori.getPreferredSize());
//        teks_nama_kategori.setMaximumSize(teks_nama_kategori.getPreferredSize());
        jTextFieldNamaKategori.setForeground(Color.LIGHT_GRAY);
//        if (jTextFieldKodeKategori.getText().equals("Masukkan Kode Kategori")) {
//            teks_nama_kategori.enable(false);
//        }
    }

    private void kesalahanID() {
        try {
            setID(jTextFieldKodeKategori.getText());
        } catch (IDException ix) {
            jTextFieldKodeKategori.setForeground(Color.LIGHT_GRAY);
            jTextFieldKodeKategori.setText("Masukkan Kode Kategori");
            jLabelErrorKode.setText(ix.getMessage());
            return;
        }
        jTextFieldKodeKategori.setText(getID());
        jLabelErrorKode.setText(" ");
        kesalahan--;
    }

    private void kesalahanNama() {
        try {
            setNama(jTextFieldNamaKategori.getText());
        } catch (NamaException nx) {
            jTextFieldNamaKategori.setForeground(Color.LIGHT_GRAY);
            jTextFieldNamaKategori.setText("Masukkan Nama Kategori");
            jLabelErrorNama.setText(nx.getMessage());
            return;
        }
        jTextFieldNamaKategori.setText(getNama());
        jLabelErrorNama.setText(" ");
        kesalahan--;
    }
}
