package com.koneksi;

import com.kategori.barang.kategoribarangform;
import com.kategori.barang.kategoribarangformArsip;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.UIManager;
import oracle.jdbc.pool.OracleDataSource;
//import com.seaglasslookandfeel.SeaGlassLookAndFeel;
//import ch.randelshofer.quaqua.BasicQuaquaLookAndFeel;
//import ch.randelshofer.quaqua.BasicQuaquaNativeLookAndFeel;
//
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */

/**
 *
 * @author rai
 */
public final class MasukArsip extends javax.swing.JFrame {

    /**
     * Creates new form masuk
     */
//    private String string_url, string_username, string_password;
    public MasukArsip() {
        initComponents();
//        setDesign();
    }

//    public String getString_url() {
//        return string_url;
//    }
//
//    public void setString_url(String string_url) {
//        this.string_url = string_url;
////        string_url = jTextField_url.getText();
//    }
//
//    public String getString_username() {
//        return string_username;
//    }
//
//    public void setString_username(String string_username) {
//        this.string_username = string_username;
////        string_username = jTextField_username.getText();
//    }
//
//    public String getString_password() {
//        return string_password;
//    }
//
//    public void setString_password(String string_password) {
//        this.string_password = string_password;
////        string_password = jPasswordField.getName();
//    }
//    public void setDesign() {
//        try {
////            UIManager.setLookAndFeel("ch.randelshofer.quaqua.BasicQuaquaLookAndFeel");
//            UIManager.setLookAndFeel("ch.randelshofer.quaqua.BasicQuaquaNativeLookAndFeel");
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }

    public JPasswordField getjPasswordField() {
        return jPasswordField;
    }

    public void setjPasswordField(JPasswordField jPasswordField) {
        this.jPasswordField = jPasswordField;
    }

    public JTextField getjTextField_url() {
        return jTextFieldURL;
    }

    public void setjTextField_url(JTextField jTextField_url) {
        this.jTextFieldURL = jTextField_url;
    }

    public JTextField getjTextField_username() {
        return jTextFieldUsername;
    }

    public void setjTextField_username(JTextField jTextField_username) {
        this.jTextFieldUsername = jTextField_username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldUsername = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jTextFieldURL = new javax.swing.JTextField();
        jLabel_username = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        jLabel_url = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton_batal = new javax.swing.JButton();
        jButton_masuk = new javax.swing.JButton();
        jButton_keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 1, 20)); // NOI18N
        jLabel1.setText("PROGRAM INPUT BARANG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(312, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jDesktopPane2.add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "form login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 2, 12))); // NOI18N

        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });

        jPasswordField.setText("jPasswordField1");

        jLabel_username.setText("USERNAME");

        jLabel_password.setText("PASSWORD");

        jLabel_url.setText("URL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_url)
                    .addComponent(jLabel_password)
                    .addComponent(jLabel_username))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldURL, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addComponent(jTextFieldUsername)
                    .addComponent(jPasswordField))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_username))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_password)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_url)
                    .addComponent(jTextFieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane2.add(jPanel2);
        jPanel2.setBounds(0, 30, 580, 160);

        jButton_batal.setText("BATAL");
        jButton_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_batalActionPerformed(evt);
            }
        });

        jButton_masuk.setText("MASUK");
        jButton_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_masukActionPerformed(evt);
            }
        });

        jButton_keluar.setText("KELUAR");
        jButton_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(jButton_keluar)
                .addGap(18, 18, 18)
                .addComponent(jButton_batal)
                .addGap(18, 18, 18)
                .addComponent(jButton_masuk)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_keluar)
                    .addComponent(jButton_batal)
                    .addComponent(jButton_masuk))
                .addGap(56, 56, 56))
        );

        jDesktopPane2.add(jPanel3);
        jPanel3.setBounds(0, 190, 580, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jButton_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_masukActionPerformed

//        koneksi k = new koneksi();
//        com.kategori.barang.kategoribarangform kbk = new kategoribarangform();
//        try {
//            k.getkoneksi();
//            JOCptionPane.showMessageDialog(this, "koneksi berhasil");
//            kbk.setVisible(true);
//
//        } catch (Exception e) {
//            k.getkoneksi();
//        }
//        if (getString_password().equals("hr") && getString_url().equals("localhost") && getString_username().equals("hr")) {
//            kbk.setVisible(true);
//        } else {
//            JOptionPane.showMessageDialog(kbk, k);
//        }
//        com.kategori.barang.kategoribarangform kbk = new kategoribarangform();
//        Connection conn = null;
//        try {
//            OracleDataSource ds;
//            ds = new OracleDataSource();
//            ds.setURL(getString_url());
//            conn = ds.getConnection(getString_username(), getString_password());
//            JOptionPane.showMessageDialog(this, "koneksi berhasil");
//            kbk.setVisible(true);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "error pada " + e.getMessage());
//            kbk.setVisible(false);
//        }
        String userName = jTextFieldUsername.getText();
        String Paswd = jPasswordField.getText();
        String url = jTextFieldURL.getText();

        Login login = new Login();
        login.setUserid(userName);
        login.setPass(Paswd);
        login.setUrl(url);

        if ((userName != null) && (Paswd != null) && (url != null)) {
            if (userName.equalsIgnoreCase("hr") && (Paswd.equalsIgnoreCase("hr")) && (url.equalsIgnoreCase("localhost"))) {
//                koneksi conn = new koneksi();
//                koneksi k=new koneksi();
//                conn.getKoneksi(userName, Paswd, url);
                com.koneksi.koneksi.getkoneksi("jdbc:Oracle:thin:@"+url+":1521:xe", userName, Paswd);
                System.out.println("Login Masuk berhasil");

//                kategoribarangform kategori = new kategoribarangform();
//                kategori.setVisible(true);
                                com.kategori.barang.kategoribarangformArsip ka=new kategoribarangformArsip();
                                ka.setVisible(true);

//                this.setVisible(false);
                this.dispose();

                jPasswordField.setText("**************");
                jTextFieldUsername.setText(" ");
                jTextFieldURL.setText(" ");
            } else {
                JOptionPane.showMessageDialog(null, "wrong user name or password or url");
            }
        }
    }//GEN-LAST:event_jButton_masukActionPerformed

    private void jButton_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_batalActionPerformed
        // TODO add your handling code here:
        jTextFieldUsername.setText("");
        jTextFieldURL.setText("");
        jPasswordField.setText("**************");
    }//GEN-LAST:event_jButton_batalActionPerformed

    private void jButton_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasukArsip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasukArsip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasukArsip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasukArsip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MasukArsip().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_batal;
    private javax.swing.JButton jButton_keluar;
    private javax.swing.JButton jButton_masuk;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_url;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldURL;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
