/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.barang;

import com.kategori.barang.kategoribarang;
import com.kategori.barang.kategoribarangkontrol;
//import com.sun.java.swing.plaf.
//import com.sun.java.swing.plaf.gtk.GTKLookAndFeel ;
import com.sun.java.swing.plaf.motif.MotifLookAndFeel;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.util.JRSaver;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author raikeiji
 */
public class daftarmenuArsip extends javax.swing.JFrame {

    /**
     * Creates new form daftarmenuArsip
     */
    public daftarmenuArsip() {
        initComponents();
        tampilkategori();
        tampilanAwal();
//        setDesign();
        LihatDaftarBarangpadaTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrameListBarang = new javax.swing.JInternalFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldJInternalFrame = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableJInternalFrame = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jButtonInternalFrameKeluar = new javax.swing.JButton();
        jButtonJInternalFrameHapus = new javax.swing.JButton();
        jButtonJInternalFrameCari = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNamaBarang = new javax.swing.JTextField();
        jTextFieldKodeBarang = new javax.swing.JTextField();
        jComboBoxKategoriBarang = new javax.swing.JComboBox();
        jComboBoxSatuan = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldQtyMax = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldQtyMin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabelGambar = new javax.swing.JLabel();
        jButtonUpload = new javax.swing.JButton();
        jLabelErrorNamaBarang = new javax.swing.JLabel();
        jLabelErrorKodeBarang = new javax.swing.JLabel();
        jLabelErrorQtyMax = new javax.swing.JLabel();
        jLabelErrorQtyMin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldRitelSetelah = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldRitelSebelum = new javax.swing.JTextField();
        jLabelErrorRitelSetelah = new javax.swing.JLabel();
        jLabelErrorRitelSebelum = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldBeliSebelum = new javax.swing.JTextField();
        jTextFieldBeliSetelah = new javax.swing.JTextField();
        jLabelErrorBeliSetelah = new javax.swing.JLabel();
        jLabelErrorBeliSebelum = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButtonCekDaftarMenu = new javax.swing.JButton();
        jButtonSimpan = new javax.swing.JButton();
        jButtonList = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();
        jButtonKeluar = new javax.swing.JButton();
        jInternalFrameCetakBarang = new javax.swing.JInternalFrame();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableJInternalFrameCetakBarang = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jTextFieldAwalCetakFrame = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldAkhirCetakFrame = new javax.swing.JTextField();
        jCheckBoxCetakFrame = new javax.swing.JCheckBox();
        jButtonCetakFrameTampil = new javax.swing.JButton();
        jButtonCetakFrameCetak = new javax.swing.JButton();
        jButtonCetakFrameKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrameListBarang.setTitle("Daftar Barang Pencarian");
        jInternalFrameListBarang.setVisible(false);

        jLabel16.setText("Data yang dicari");

        jTextFieldJInternalFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJInternalFrameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableJInternalFrame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Kategori", "Harga Jual"
            }
        ));
        jTableJInternalFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableJInternalFrameMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableJInternalFrame);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonInternalFrameKeluar.setText("KELUAR");
        jButtonInternalFrameKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInternalFrameKeluarActionPerformed(evt);
            }
        });

        jButtonJInternalFrameHapus.setText("HAPUS");
        jButtonJInternalFrameHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJInternalFrameHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonJInternalFrameHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonInternalFrameKeluar)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInternalFrameKeluar)
                    .addComponent(jButtonJInternalFrameHapus))
                .addContainerGap())
        );

        jButtonJInternalFrameCari.setText("CARI");
        jButtonJInternalFrameCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJInternalFrameCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameListBarangLayout = new javax.swing.GroupLayout(jInternalFrameListBarang.getContentPane());
        jInternalFrameListBarang.getContentPane().setLayout(jInternalFrameListBarangLayout);
        jInternalFrameListBarangLayout.setHorizontalGroup(
            jInternalFrameListBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jInternalFrameListBarangLayout.createSequentialGroup()
                .addGroup(jInternalFrameListBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameListBarangLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonJInternalFrameCari))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameListBarangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jInternalFrameListBarangLayout.setVerticalGroup(
            jInternalFrameListBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameListBarangLayout.createSequentialGroup()
                .addGroup(jInternalFrameListBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrameListBarangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonJInternalFrameCari)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jInternalFrameListBarang);
        jInternalFrameListBarang.setBounds(0, 70, 450, 390);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("DAFTAR BARANG");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        jLabel2.setText("Digunakan untuk manambah, mengedit, menghapus, dan mencari daftar barang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );

        jDesktopPane1.add(jPanel1);
        jPanel1.setBounds(0, 0, 660, 60);

        jLabel3.setText("Nama Barang");

        jLabel4.setText("Kategori Barang");

        jLabel5.setText("Kode Barang");

        jLabel6.setText("Satuan");

        jTextFieldNamaBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNamaBarangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldNamaBarangMouseEntered(evt);
            }
        });
        jTextFieldNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaBarangActionPerformed(evt);
            }
        });
        jTextFieldNamaBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNamaBarangKeyReleased(evt);
            }
        });

        jTextFieldKodeBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldKodeBarangMouseClicked(evt);
            }
        });
        jTextFieldKodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKodeBarangActionPerformed(evt);
            }
        });

        jComboBoxKategoriBarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        jComboBoxKategoriBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxKategoriBarangActionPerformed(evt);
            }
        });

        jComboBoxSatuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Buah", "Lembar", "Meter", "Liter" }));

        jLabel7.setText("Qty Max");

        jTextFieldQtyMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldQtyMaxMouseClicked(evt);
            }
        });
        jTextFieldQtyMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldQtyMaxKeyReleased(evt);
            }
        });

        jLabel8.setText("Qty Min");

        jTextFieldQtyMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldQtyMinMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextFieldQtyMinMouseReleased(evt);
            }
        });
        jTextFieldQtyMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldQtyMinKeyReleased(evt);
            }
        });

        jLabel9.setText("Foto Barang");

        jLabelGambar.setText("upload foto anda");

        jButtonUpload.setText("Upload");
        jButtonUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadActionPerformed(evt);
            }
        });

        jLabelErrorNamaBarang.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorNamaBarang.setText("jLabel16");

        jLabelErrorKodeBarang.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorKodeBarang.setText("jLabel17");

        jLabelErrorQtyMax.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorQtyMax.setText("jLabel16");

        jLabelErrorQtyMin.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorQtyMin.setText("jLabel17");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelErrorQtyMax)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelErrorNamaBarang)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldNamaBarang)
                                        .addComponent(jComboBoxKategoriBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxSatuan, 0, 140, Short.MAX_VALUE))
                                    .addComponent(jTextFieldQtyMax, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldQtyMin, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelErrorKodeBarang)
                                    .addComponent(jTextFieldKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelErrorQtyMin))))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonUpload)
                            .addComponent(jLabel9)
                            .addComponent(jLabelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonUpload))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelErrorNamaBarang)
                            .addComponent(jLabelErrorKodeBarang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxKategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldQtyMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldQtyMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelErrorQtyMax)
                    .addComponent(jLabelErrorQtyMin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jPanel2);
        jPanel2.setBounds(0, 60, 660, 200);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informasi Penjualan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 12))); // NOI18N

        jLabel11.setText("Ritel Setelah PPN");

        jTextFieldRitelSetelah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldRitelSetelahMouseClicked(evt);
            }
        });
        jTextFieldRitelSetelah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRitelSetelahActionPerformed(evt);
            }
        });
        jTextFieldRitelSetelah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldRitelSetelahKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRitelSetelahKeyTyped(evt);
            }
        });

        jLabel12.setText("Ritel Sebelum PPN");

        jTextFieldRitelSebelum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldRitelSebelumMouseClicked(evt);
            }
        });
        jTextFieldRitelSebelum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldRitelSebelumKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRitelSebelumKeyTyped(evt);
            }
        });

        jLabelErrorRitelSetelah.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorRitelSetelah.setText("jLabel16");

        jLabelErrorRitelSebelum.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorRitelSebelum.setText("jLabel16");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldRitelSetelah, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addComponent(jLabelErrorRitelSetelah))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelErrorRitelSebelum)
                    .addComponent(jTextFieldRitelSebelum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldRitelSetelah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldRitelSebelum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelErrorRitelSetelah)
                    .addComponent(jLabelErrorRitelSebelum))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jPanel3);
        jPanel3.setBounds(0, 260, 660, 100);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informasi Pembelian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 12))); // NOI18N

        jLabel13.setText("Beli Setelah PPN");

        jLabel14.setText("Beli Sebelem PPN");

        jTextFieldBeliSebelum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBeliSebelumMouseClicked(evt);
            }
        });
        jTextFieldBeliSebelum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBeliSebelumKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBeliSebelumKeyTyped(evt);
            }
        });

        jTextFieldBeliSetelah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBeliSetelahMouseClicked(evt);
            }
        });
        jTextFieldBeliSetelah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBeliSetelahKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBeliSetelahKeyTyped(evt);
            }
        });

        jLabelErrorBeliSetelah.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorBeliSetelah.setText("jLabel16");

        jLabelErrorBeliSebelum.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorBeliSebelum.setText("jLabel16");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldBeliSetelah, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jLabelErrorBeliSetelah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldBeliSebelum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorBeliSebelum))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldBeliSetelah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldBeliSebelum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelErrorBeliSebelum)
                    .addComponent(jLabelErrorBeliSetelah))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jPanel4);
        jPanel4.setBounds(0, 360, 660, 110);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonCekDaftarMenu.setText("Cetak Daftar Menu");
        jButtonCekDaftarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCekDaftarMenuActionPerformed(evt);
            }
        });

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jButtonList.setText("List");
        jButtonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListActionPerformed(evt);
            }
        });

        jButtonBatal.setText("Batal");
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });

        jButtonKeluar.setText("Keluar");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCekDaftarMenu)
                .addGap(18, 18, 18)
                .addComponent(jButtonSimpan)
                .addGap(18, 18, 18)
                .addComponent(jButtonList)
                .addGap(18, 18, 18)
                .addComponent(jButtonBatal)
                .addGap(148, 148, 148)
                .addComponent(jButtonKeluar)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCekDaftarMenu)
                    .addComponent(jButtonSimpan)
                    .addComponent(jButtonList)
                    .addComponent(jButtonBatal)
                    .addComponent(jButtonKeluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jPanel5);
        jPanel5.setBounds(0, 470, 660, 50);

        jInternalFrameCetakBarang.setTitle("Frame Cetak Laporan Barang");
        jInternalFrameCetakBarang.setVisible(false);

        jTableJInternalFrameCetakBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Kategori", "Harga Jual"
            }
        ));
        jTableJInternalFrameCetakBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableJInternalFrameCetakBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableJInternalFrameCetakBarang);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel18.setText("s/d");

        jCheckBoxCetakFrame.setText("pilih semua");
        jCheckBoxCetakFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxCetakFrameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jTextFieldAwalCetakFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAkhirCetakFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBoxCetakFrame))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAwalCetakFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldAkhirCetakFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxCetakFrame)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        jButtonCetakFrameTampil.setText("TAMPIL");
        jButtonCetakFrameTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCetakFrameTampilActionPerformed(evt);
            }
        });

        jButtonCetakFrameCetak.setText("CETAK");
        jButtonCetakFrameCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCetakFrameCetakActionPerformed(evt);
            }
        });

        jButtonCetakFrameKeluar.setText("KELUAR");
        jButtonCetakFrameKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCetakFrameKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameCetakBarangLayout = new javax.swing.GroupLayout(jInternalFrameCetakBarang.getContentPane());
        jInternalFrameCetakBarang.getContentPane().setLayout(jInternalFrameCetakBarangLayout);
        jInternalFrameCetakBarangLayout.setHorizontalGroup(
            jInternalFrameCetakBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jInternalFrameCetakBarangLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCetakFrameTampil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCetakFrameCetak)
                .addGap(5, 5, 5)
                .addComponent(jButtonCetakFrameKeluar)
                .addContainerGap())
        );
        jInternalFrameCetakBarangLayout.setVerticalGroup(
            jInternalFrameCetakBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameCetakBarangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrameCetakBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrameCetakBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonCetakFrameKeluar)
                        .addComponent(jButtonCetakFrameTampil)
                        .addComponent(jButtonCetakFrameCetak)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDesktopPane1.add(jInternalFrameCetakBarang);
        jInternalFrameCetakBarang.setBounds(0, 0, 550, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public final void setDesign() {
        try {
//            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
        } catch (Exception e) {
        }
    }

    public void tampilkategori() {
        try {
            jComboBoxKategoriBarang.removeAllItems();
            List<kategoribarang> daftarbarang = com.kategori.barang.kategoribarangkontrol.getKoneksiKategori().lihatSeluruhKateogri();
            for (int i = 0; i < daftarbarang.size(); i++) {
                kategoribarang elem = daftarbarang.get(i);
                jComboBoxKategoriBarang.addItem(elem.getKode_kategori() + " " + elem.getNama_kategori());
            }
        } catch (SQLException ex) {
            Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void jTextFieldNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaBarangActionPerformed
    }//GEN-LAST:event_jTextFieldNamaBarangActionPerformed

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    private void jTextFieldRitelSetelahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRitelSetelahKeyReleased
////        String a = jTextFieldRitelSetelah.getText();
////        double temp;
////        if (a.isEmpty()) {
////            a = "0";
////        } else {
////            a = a.replaceAll("\\.", "");
////            a = NumberFormat.getNumberInstance(Locale.ENGLISH).format(Double.parseDouble(a));
////            a = a.replace(",", ".");
////        }
////        jTextFieldRitelSetelah.setText(a);
        String ritelSetelah = jTextFieldRitelSetelah.getText();

        try {
            if (ritelSetelah.isEmpty()) {
                jTextFieldRitelSetelah.setText("0");
                jTextFieldRitelSebelum.setText("0");
            }
            Double harga = Double.parseDouble(ritelSetelah);
            Double setelah = harga - (harga * 0.1);
            jTextFieldRitelSebelum.setText(setelah.toString());
            jTextFieldRitelSebelum.setEnabled(true);
            jTextFieldRitelSebelum.setForeground(Color.BLACK);
            repaint();
            revalidate();

        } catch (Exception ex) {
            jTextFieldRitelSetelah.setText("");
            jTextFieldRitelSetelah.requestFocus();
            Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldRitelSetelahKeyReleased

    private void jTextFieldRitelSetelahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRitelSetelahKeyTyped
        char keyChar = evt.getKeyChar();
        if (!((keyChar >= '0') && (keyChar <= '9') || (keyChar == (8)) && (keyChar == '.'))) {
            evt.setKeyChar((char) 0);
        }
    }//GEN-LAST:event_jTextFieldRitelSetelahKeyTyped

    private void jTextFieldRitelSetelahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldRitelSetelahMouseClicked
        jTextFieldRitelSetelah.setEnabled(true);
        if (jTextFieldRitelSetelah.getText().equals("0")) {
            jTextFieldRitelSetelah.setText("");
            jTextFieldRitelSetelah.setForeground(Color.BLACK);
            repaint();
            revalidate();
        }
    }//GEN-LAST:event_jTextFieldRitelSetelahMouseClicked

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        tampilanAwal();
//        jComboBoxKategoriBarang.setSelectedIndex(1);
//        jComboBoxSatuan.setSelectedItem(1);
//        jComboBoxKategoriBarang.getItemAt(1);
//        jComboBoxSatuan.getItemAt(1);
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jButtonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListActionPerformed
        jInternalFrameListBarang.setVisible(true);
    }//GEN-LAST:event_jButtonListActionPerformed

    private void jButtonInternalFrameKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInternalFrameKeluarActionPerformed
//        dispose();
        jInternalFrameListBarang.setVisible(false);

    }//GEN-LAST:event_jButtonInternalFrameKeluarActionPerformed

    private void jTextFieldRitelSebelumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRitelSebelumKeyReleased
//        String a = jTextFieldRitelSebelum.getText();
//        double temp;
//        if (a.isEmpty()) {
//            a = "0";
//        } else {
//            a = a.replaceAll("\\.", "");
//            a = NumberFormat.getNumberInstance(Locale.ENGLISH).format(Double.parseDouble(a));
//            a = a.replace(",", ".");
//        }
//        jTextFieldRitelSebelum.setText(a);
        String ritelSebelum = jTextFieldRitelSebelum.getText();

        try {
            if (ritelSebelum.isEmpty()) {
                jTextFieldRitelSebelum.setText("0");
                jTextFieldRitelSetelah.setText("0");
            }
            Double harga = Double.parseDouble(ritelSebelum);
            Double sebelum = harga + (harga * 0.1);
            jTextFieldRitelSetelah.setText(sebelum.toString());
            jTextFieldRitelSetelah.setEnabled(true);
            jTextFieldRitelSetelah.setForeground(Color.BLACK);
            repaint();
            revalidate();

        } catch (Exception ex) {
            jTextFieldRitelSebelum.setText("");
            jTextFieldRitelSebelum.requestFocus();
            Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTextFieldRitelSebelumKeyReleased

    private void jTextFieldRitelSebelumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRitelSebelumKeyTyped
        char keyChar = evt.getKeyChar();
        if (!((keyChar >= '0') && (keyChar <= '9') || (keyChar == (8)) && (keyChar == '.'))) {
            evt.setKeyChar((char) 0);
        }
    }//GEN-LAST:event_jTextFieldRitelSebelumKeyTyped

    private void jTextFieldRitelSebelumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldRitelSebelumMouseClicked
        jTextFieldRitelSebelum.setEnabled(true);
        if (jTextFieldRitelSebelum.getText().equals("0")) {
            jTextFieldRitelSebelum.setText("");
            jTextFieldRitelSebelum.setForeground(Color.BLACK);
            repaint();
            revalidate();
        }
    }//GEN-LAST:event_jTextFieldRitelSebelumMouseClicked

    private void jTextFieldBeliSetelahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBeliSetelahKeyReleased
//        String a = jTextFieldBeliSetelah.getText();
//        double temp;
//        if (a.isEmpty()) {
//            a = "0";
//        } else {
//            a = a.replaceAll("\\.", "");
//            a = NumberFormat.getNumberInstance(Locale.ENGLISH).format(Double.parseDouble(a));
//            a = a.replace(",", ".");
//        }
//        jTextFieldBeliSetelah.setText(a);
        String beliSetelah = jTextFieldBeliSetelah.getText();

        try {

            if (beliSetelah.isEmpty()) {
                jTextFieldBeliSetelah.setText("0");
                jTextFieldBeliSebelum.setText("0");
            }
            Double harga = Double.parseDouble(beliSetelah);
            Double setelah = harga - (harga * 0.1);
            jTextFieldBeliSebelum.setText(setelah.toString());
            jTextFieldBeliSebelum.setEnabled(true);
            jTextFieldBeliSebelum.setForeground(Color.BLACK);
            repaint();
            revalidate();

        } catch (Exception ex) {
            jTextFieldBeliSetelah.setText("");
            jTextFieldBeliSetelah.requestFocus();
            Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldBeliSetelahKeyReleased

    private void jTextFieldBeliSetelahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBeliSetelahKeyTyped
        char keyChar = evt.getKeyChar();
        if (!((keyChar >= '0') && (keyChar <= '9') || (keyChar == (8)) && (keyChar == '.'))) {
            evt.setKeyChar((char) 0);
        }
    }//GEN-LAST:event_jTextFieldBeliSetelahKeyTyped

    private void jTextFieldBeliSetelahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBeliSetelahMouseClicked
        jTextFieldBeliSetelah.setEnabled(true);
        if (jTextFieldBeliSetelah.getText().equals("0")) {
            jTextFieldBeliSetelah.setText("");
            jTextFieldBeliSetelah.setForeground(Color.BLACK);
            repaint();
            revalidate();
        }
    }//GEN-LAST:event_jTextFieldBeliSetelahMouseClicked

    private void jTextFieldBeliSebelumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBeliSebelumKeyReleased
//        String a = jTextFieldBeliSebelum.getText();
//        double temp;
//        if (a.isEmpty()) {
//            a = "0";
//        } else {
//            a = a.replaceAll("\\.", "");
//            a = NumberFormat.getNumberInstance(Locale.ENGLISH).format(Double.parseDouble(a));
//            a = a.replace(",", ".");
//        }
//        jTextFieldBeliSebelum.setText(a);
        String beliSebelum = jTextFieldBeliSebelum.getText();

        try {
            if (beliSebelum.isEmpty()) {
                jTextFieldBeliSebelum.setText("0");
                jTextFieldBeliSetelah.setText("0");
            }
            Double harga = Double.parseDouble(beliSebelum);
            Double sebelum = harga + (harga * 0.1);
            jTextFieldBeliSetelah.setText(sebelum.toString());
            jTextFieldBeliSetelah.setEnabled(true);
            jTextFieldBeliSetelah.setForeground(Color.BLACK);
            repaint();
            revalidate();

        } catch (NumberFormatException ex) {
            jTextFieldBeliSebelum.setText("");
            jTextFieldBeliSebelum.requestFocus();
            Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldBeliSebelumKeyReleased

    private void jTextFieldBeliSebelumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBeliSebelumKeyTyped
        char keyChar = evt.getKeyChar();
        if (!((keyChar >= '0') && (keyChar <= '9') || (keyChar == (8)) && (keyChar == '.'))) {
            evt.setKeyChar((char) 0);
        }
    }//GEN-LAST:event_jTextFieldBeliSebelumKeyTyped

    private void jTextFieldBeliSebelumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBeliSebelumMouseClicked
        jTextFieldBeliSebelum.setEnabled(true);
        if (jTextFieldBeliSebelum.getText().equals("0")) {
            jTextFieldBeliSebelum.setText("");
            jTextFieldBeliSebelum.setForeground(Color.BLACK);
            repaint();
            revalidate();
        }
    }//GEN-LAST:event_jTextFieldBeliSebelumMouseClicked

    private void jTextFieldNamaBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNamaBarangMouseClicked
        jTextFieldNamaBarang.setEnabled(true);

        if (jTextFieldNamaBarang.getText().equals("Masukkan Nama Barang")) {
            jTextFieldNamaBarang.setText("");
            jTextFieldNamaBarang.setForeground(Color.BLACK);
            repaint();
            revalidate();
        } else {
            jTextFieldNamaBarang.setText(jTextFieldNamaBarang.getText() + "");
            jTextFieldNamaBarang.setForeground(Color.BLACK);
            repaint();
            revalidate();
        }


    }//GEN-LAST:event_jTextFieldNamaBarangMouseClicked

    private void jTextFieldKodeBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldKodeBarangMouseClicked
        jTextFieldKodeBarang.setEnabled(true);
        if (!jTextFieldKodeBarang.getText().isEmpty()) {
            jTextFieldKodeBarang.setText(jTextFieldKodeBarang.getText() + "");
            jTextFieldKodeBarang.setForeground(Color.BLACK);
            repaint();
            revalidate();
        }

//        String kode = jTextFieldKodeBarang.getText();
//        barang b = new barang();
//        b.setKodeBarang(kode);
//        if (kode.equals("") || kode == null) {
//            JOptionPane.showMessageDialog(rootPane, "Kode harus diisi");
//        } else {
//            try {
//                BarangKontrol kbk = new BarangKontrol(com.koneksi.koneksi.getkoneksi());
//                String namakategori = BarangKontrol.getKoneksi().carikategoribarang(kb);
//                jTextFieldNamaBarang.setEnabled(true);
//                jTextFieldNamaBarang.setText(namakategori);
//                jTextFieldNamaBarang.setForeground(Color.BLACK);
//                repaint();
//                revalidate();
//                if (jTextFieldNamaBarang.getText().isEmpty()) {
//                    button_simpan.setText("SIMPAN");
//                } else {
//                    button_simpan.setText("UPDATE");
//                }
//            } catch (Exception e) {
//                jTextFieldNamaBarang.setText("");
//                jTextFieldNamaBarang.requestFocus();
//            }
//        }
    }//GEN-LAST:event_jTextFieldKodeBarangMouseClicked

    private void jTextFieldQtyMaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldQtyMaxMouseClicked
        jTextFieldQtyMax.setEnabled(true);
        if (jTextFieldQtyMax.getText().equals("0")) {
            jTextFieldQtyMax.setText("");
            jTextFieldQtyMax.setForeground(Color.BLACK);
            repaint();
            revalidate();
        }
    }//GEN-LAST:event_jTextFieldQtyMaxMouseClicked

    private void jTextFieldQtyMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldQtyMinMouseClicked
        jTextFieldQtyMin.setEnabled(true);
        if (jTextFieldQtyMin.getText().equals("0")) {
            jTextFieldQtyMin.setText("");
            jTextFieldQtyMin.setForeground(Color.BLACK);
            repaint();
            revalidate();
        }
    }//GEN-LAST:event_jTextFieldQtyMinMouseClicked

    private void jTextFieldKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKodeBarangActionPerformed
//        List<kategoribarang> daftarbarang = null;
//        try {
//            daftarbarang = com.kategori.barang.kategoribarangkontrol.getKoneksiKategori().lihatSeluruhKateogri();
//        } catch (SQLException ex) {
//            Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        for (int i = 0; i < daftarbarang.size(); i++) {
//            kategoribarang elem = daftarbarang.get(i);
//            jComboBoxKategoriBarang.addItem(elem.getKode_kategori() + " " + elem.getNama_kategori());
//        }
        String kode = jTextFieldKodeBarang.getText();
        barang kb = new barang();
        kb.setKodeBarang(kode);
//        BarangKontrol kbk = new BarangKontrol(com.koneksi.koneksi.getkoneksi(com.koneksi.koneksi.getkoneksi("hr","hr","jdbc:Oracle:thin:@localhost:1521:xe")));
        try {
            String namakategori = BarangKontrol.getKoneksi().cariNamaBarang(kb);
            String gambar = BarangKontrol.getKoneksi().cariGambar(kb);
            String qtmax = BarangKontrol.getKoneksi().cariQuantityMax(kb);
            String qtmin = BarangKontrol.getKoneksi().cariQuantityMin(kb);
            String ritelsetelah = BarangKontrol.getKoneksi().cariRitelSesudah(kb);
            String ritelsebelum = BarangKontrol.getKoneksi().cariRitelSebelum(kb);
            String belisetelah = BarangKontrol.getKoneksi().cariBeliSesudah(kb);
            String belisebelum = BarangKontrol.getKoneksi().cariBeliSebelum(kb);
            String satuan = BarangKontrol.getKoneksi().cariSatuan(kb);

            jTextFieldNamaBarang.setEnabled(true);
            jTextFieldNamaBarang.setText(namakategori);
            jTextFieldNamaBarang.setForeground(Color.BLACK);

            jTextFieldQtyMax.setEnabled(true);
            jTextFieldQtyMax.setText(qtmax);
            jTextFieldQtyMax.setForeground(Color.BLACK);

            jTextFieldQtyMin.setEnabled(true);
            jTextFieldQtyMin.setText(qtmin);
            jTextFieldQtyMin.setForeground(Color.BLACK);

            jLabelGambar.setEnabled(true);
            jLabelGambar.setText(gambar);

            jTextFieldRitelSetelah.setEnabled(true);
            jTextFieldRitelSetelah.setText(ritelsetelah);
            jTextFieldRitelSetelah.setForeground(Color.BLACK);

            jTextFieldRitelSebelum.setEnabled(true);
            jTextFieldRitelSebelum.setText(ritelsebelum);
            jTextFieldRitelSebelum.setForeground(Color.BLACK);

            jTextFieldBeliSetelah.setEnabled(true);
            jTextFieldBeliSetelah.setText(belisetelah);
            jTextFieldBeliSetelah.setForeground(Color.BLACK);

            jTextFieldBeliSebelum.setEnabled(true);
            jTextFieldBeliSebelum.setText(belisebelum);
            jTextFieldBeliSebelum.setForeground(Color.BLACK);

            repaint();
            revalidate();

            jComboBoxSatuan.setSelectedItem(satuan);

            if (!jTextFieldNamaBarang.getText().isEmpty()) {
                jComboBoxKategoriBarang.setEnabled(false);
                jComboBoxKategoriBarang.setEditable(false);
                jButtonSimpan.setText("Update");
            } else {
                jButtonSimpan.setText("Simpan");
                JOptionPane.showMessageDialog(rootPane, "Kodebarang yang anda masukkan tidak ada dalam database");
            }

//             barang b = new barang();
//        kategoribarang kabar = new kategoribarang();
//            int i = jComboBoxKategoriBarang.getSelectedIndex();
//        String kodekategori = jComboBoxKategoriBarang.getItemAt(i).toString();
//        String[] temp = kodekategori.split(" ");
//        kabar.setKode_kategori(temp[0]);
//        kabar.setNama_kategori(temp[1]);
//                teks_nama_kategori.setEnabled(true);
//                teks_nama_kategori.setText(namakategori);
//                teks_nama_kategori.setForeground(Color.BLACK);
//                repaint();
//                revalidate();
//                if (teks_nama_kategori.getText().isEmpty()) {
//                    button_simpan.setText("SIMPAN");
//                } else {
//                    button_simpan.setText("UPDATE");
//                }
        } catch (Exception ex) {
            Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldKodeBarangActionPerformed

    private void jTextFieldQtyMinMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldQtyMinMouseReleased
        String qtyMin = jTextFieldQtyMin.getText();
        try {
            if (qtyMin.isEmpty()) {
                qtyMin = "0";
            } else {
                qtyMin = qtyMin.replace(".", "");
                qtyMin = NumberFormat.getInstance(Locale.ENGLISH).format(Double.parseDouble(qtyMin));
                qtyMin = qtyMin.replace(",", ".");
            }
            jTextFieldQtyMin.setText(qtyMin);
        } catch (Exception e) {
            jTextFieldQtyMin.setText("0");
            jTextFieldQtyMin.requestFocus();
            Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jTextFieldQtyMinMouseReleased

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        barang b = new barang();
        kategoribarang kabar = new kategoribarang();

        int i = jComboBoxKategoriBarang.getSelectedIndex();
        String kodekategori = jComboBoxKategoriBarang.getItemAt(i).toString();
        String[] temp = kodekategori.split(" ");
        kabar.setKode_kategori(temp[0]);
        kabar.setNama_kategori(temp[1]);

        b.setBeliSebelum(Double.parseDouble(jTextFieldBeliSebelum.getText()));
        b.setBeliSesudah(Double.parseDouble(jTextFieldBeliSetelah.getText()));
        b.setKategori(kabar);
        b.setKodeBarang(jTextFieldKodeBarang.getText());
        b.setNamaBarang(jTextFieldNamaBarang.getText());
        b.setQuantityMax(Double.parseDouble(jTextFieldQtyMax.getText()));
        b.setQuantityMin(Double.parseDouble(jTextFieldQtyMin.getText()));
        b.setRitelSebelum(Double.parseDouble(jTextFieldRitelSebelum.getText()));
        b.setRitelSesudah(Double.parseDouble(jTextFieldRitelSetelah.getText()));
        b.setSatuan(jComboBoxSatuan.getSelectedItem().toString());
        b.setGambar(jLabelGambar.getText());
        if (jButtonSimpan.getText().equals("Simpan")) {
            try {
                BarangKontrol.getKoneksi().tambahKategori(b);
                JOptionPane.showMessageDialog(rootPane, "DATA TELAH MASUK KE DATABASE");
            } catch (SQLException ex) {
                Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                BarangKontrol.getKoneksi().updateBarang(b);
                JOptionPane.showMessageDialog(rootPane, "DATA TELAH DIUPDATE KE DATABASE");
            } catch (SQLException ex) {
                Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jComboBoxKategoriBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKategoriBarangActionPerformed
        if (jComboBoxKategoriBarang.getSelectedIndex() >= 0) {
            try {
                barang brg = new barang();
                kategoribarang kategori = new kategoribarang();
                kategori.setKode_kategori(jComboBoxKategoriBarang.getSelectedItem().toString().substring(0, 3));
                brg.setKategori(kategori);

                String kode_kategori = jComboBoxKategoriBarang.getSelectedItem().toString().substring(0, 3);

                String kode = BarangKontrol.getKoneksi().cariNomorTerakhir(brg).trim();
//                System.out.println(kode);

//                 if(kateg=="002"){
//                    String urlGambar = "src/icon/simpan.jpg";
//                    ImageIcon ii = new ImageIcon(urlGambar);
//                    jLabelPhotoProduk.setIcon(ii);
//                }
                jTextFieldKodeBarang.setText(kode_kategori + kode);
                jTextFieldKodeBarang.setEnabled(true);
//                jTextFieldKodeBarang.setText("");
                jTextFieldKodeBarang.setForeground(Color.BLACK);
                repaint();
                revalidate();

                if (jTextFieldKodeBarang.getText().equals("0")) {
                    List<kategoribarang> daftarbarang = null;
                    try {
                        daftarbarang = com.kategori.barang.kategoribarangkontrol.getKoneksiKategori().lihatSeluruhKateogri();
                    } catch (SQLException ex) {
                        Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    for (int i = 0; i < daftarbarang.size(); i++) {
                        kategoribarang elem = daftarbarang.get(i);
                        jComboBoxKategoriBarang.addItem(elem.getKode_kategori() + " " + elem.getNama_kategori());
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jComboBoxKategoriBarangActionPerformed

    private void jTextFieldQtyMaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQtyMaxKeyReleased
        String qtyMax = jTextFieldQtyMax.getText();

        try {
            if (qtyMax.isEmpty()) {
                qtyMax = "0";
            } else {

                qtyMax = qtyMax.replace(".", "");
                qtyMax = NumberFormat.getInstance(Locale.ENGLISH).format(Double.parseDouble(qtyMax));
                qtyMax = qtyMax.replace(",", ".");
//                NumberFormat number = NumberFormat.getInstance();
//                number.setMinimumIntegerDigits(0);
//                number.setGroupingUsed(true);
//                double bil = Double.parseDouble(qtyMax);
//                System.out.println(number.format(bil).toString());
//                text_QtyMax.setText(number.format(bil).toString());
            }
            jTextFieldQtyMax.setText(qtyMax);

        } catch (Exception e) {
            jTextFieldQtyMax.setText("0");
            jTextFieldQtyMax.requestFocus();
            Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_jTextFieldQtyMaxKeyReleased

    private void jTextFieldQtyMinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQtyMinKeyReleased
        String qtyMin = jTextFieldQtyMin.getText();
        try {
            if (qtyMin.isEmpty()) {
                qtyMin = "0";
            } else {
                qtyMin = qtyMin.replace(".", "");
                qtyMin = NumberFormat.getInstance(Locale.ENGLISH).format(Double.parseDouble(qtyMin));
                qtyMin = qtyMin.replace(",", ".");
            }
            jTextFieldQtyMin.setText(qtyMin);
        } catch (Exception e) {
            jTextFieldQtyMin.setText("0");
            jTextFieldQtyMin.requestFocus();
            Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jTextFieldQtyMinKeyReleased

    private void jTextFieldRitelSetelahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRitelSetelahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRitelSetelahActionPerformed

    private void jTextFieldJInternalFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJInternalFrameActionPerformed
        lihatdaftarbarang();
    }//GEN-LAST:event_jTextFieldJInternalFrameActionPerformed

    public void lihatdaftarbarang() {
        String key = jTextFieldJInternalFrame.getText();
        try {
            List<barang> listKategori = BarangKontrol.getKoneksi().CaridariLIST(key);
            TabelModelBarang model = new TabelModelBarang(listKategori);
            jTableJInternalFrame.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void LihatDaftarBarangpadaTabel() {
        try {
            List<barang> listKategori = BarangKontrol.getKoneksi().lihatSeluruhKateogri();
            TabelModelBarang model = new TabelModelBarang(listKategori);
            jTableJInternalFrame.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jTableJInternalFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableJInternalFrameMouseClicked
        int baris = jTableJInternalFrame.getSelectedRow();

        String kodebarang = jTableJInternalFrame.getValueAt(baris, 0).toString();
        String namabarang = jTableJInternalFrame.getValueAt(baris, 1).toString();
        String ritelsesudah = jTableJInternalFrame.getValueAt(baris, 3).toString();

        jTextFieldKodeBarang.setText(kodebarang);
        jTextFieldNamaBarang.setText(namabarang);
        jTextFieldRitelSetelah.setText(ritelsesudah);

        List<barang> listKategori = null;
        try {
            listKategori = BarangKontrol.getKoneksi().lihatKategori();
        } catch (SQLException ex) {
            Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
        }
        TabelModelBarang model = new TabelModelBarang(listKategori);
//            jTableJInternalFrame.setModel(model);
        jTableJInternalFrame.setValueAt(baris, baris, 2);

        jTextFieldJInternalFrame.setText(jTextFieldKodeBarang.getText());
//        button_batal.setEnabled(true);
//        button_simpan.setEnabled(true);
//        button_hapus.setEnabled(true);
    }//GEN-LAST:event_jTableJInternalFrameMouseClicked

    private void jButtonJInternalFrameCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJInternalFrameCariActionPerformed
        String key = jTextFieldJInternalFrame.getText();
        try {
            List<barang> listKategori = BarangKontrol.getKoneksi().CaridariLIST(key);
            TabelModelBarang model = new TabelModelBarang(listKategori);
            model.fireTableDataChanged();
            jTableJInternalFrame.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonJInternalFrameCariActionPerformed

    private void jButtonUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Image files", "jpg", "bmp", "png"));
        chooser.setAcceptAllFileFilterUsed(false);
        int jes = chooser.showOpenDialog(this);
        if (jes == chooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            jLabelGambar.setText(f.getAbsolutePath());
            jLabelGambar.setIcon(new ImageIcon(f.getAbsolutePath()));
            System.out.println(f.getAbsolutePath());

        }

    }//GEN-LAST:event_jButtonUploadActionPerformed

    private void jTextFieldNamaBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNamaBarangKeyReleased
        String key = jTextFieldJInternalFrame.getText();
        try {
            List<barang> listKategori = BarangKontrol.getKoneksi().CaridariLIST(key);
            TabelModelBarang model = new TabelModelBarang(listKategori);
            model.fireTableDataChanged();
            jTableJInternalFrame.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldNamaBarangKeyReleased

    private void jButtonJInternalFrameHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJInternalFrameHapusActionPerformed
        String kodebarangJinternalFrame = jTextFieldJInternalFrame.getText();
        barang b = new barang();
        b.setKodeBarang(kodebarangJinternalFrame);
        try {
            BarangKontrol.getKoneksi().deleteBarang(b);
            JOptionPane.showMessageDialog(rootPane, "DATA TELAH TERHAPUS DARI DATABASE");
        } catch (SQLException ex) {
            Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
        }
        LihatDaftarBarangpadaTabel();
    }//GEN-LAST:event_jButtonJInternalFrameHapusActionPerformed

    private void jButtonCekDaftarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCekDaftarMenuActionPerformed
        jInternalFrameCetakBarang.setVisible(true);
    }//GEN-LAST:event_jButtonCekDaftarMenuActionPerformed

    private void jTableJInternalFrameCetakBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableJInternalFrameCetakBarangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableJInternalFrameCetakBarangMouseClicked

    private void jButtonCetakFrameCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCetakFrameCetakActionPerformed
        Connection kon = null;
        kon = new com.koneksi.koneksi().getkoneksi2();
        String reportSource = "";

        String kowal = jTextFieldAwalCetakFrame.getText();
        String kohir = jTextFieldAkhirCetakFrame.getText();

        if (jCheckBoxCetakFrame.isSelected()) {
            reportSource = "./src/com/barang/DaftarMenuArsip.jasper";
        } else {

            reportSource = "./laporan/LaporanCetakBarangdenganParameter.jasper";
        }
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("kodeawal", kowal);
        params.put("kodeakhir", kohir);
        try {
            JasperPrint jasperPrint = JasperFillManager.fillReport(reportSource, params, kon);
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonCetakFrameCetakActionPerformed

    private void jButtonCetakFrameKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCetakFrameKeluarActionPerformed
        jInternalFrameCetakBarang.dispose();
    }//GEN-LAST:event_jButtonCetakFrameKeluarActionPerformed

    private void jButtonCetakFrameTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCetakFrameTampilActionPerformed
        if (jCheckBoxCetakFrame.isSelected()) {
            try {
                List<barang> listKategori = BarangKontrol.getKoneksi().lihatSeluruhKateogri();
                TabelModelBarang model = new TabelModelBarang(listKategori);
                jTableJInternalFrameCetakBarang.setModel(model);
            } catch (SQLException ex) {
                Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            String kolomAwal = jTextFieldAwalCetakFrame.getText();
            String kolomAkhir = jTextFieldAkhirCetakFrame.getText();
            try {
                List<barang> listKategori = BarangKontrol.getKoneksi().TampilTabelCetak(kolomAwal, kolomAkhir);
                TabelModelBarang model = new TabelModelBarang(listKategori);
                model.fireTableDataChanged();
                jTableJInternalFrameCetakBarang.setModel(model);
            } catch (SQLException ex) {
                Logger.getLogger(daftarmenuArsip.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonCetakFrameTampilActionPerformed

    private void jCheckBoxCetakFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxCetakFrameMouseClicked
        if (jCheckBoxCetakFrame.isSelected()) {
            jTextFieldAwalCetakFrame.setText("");
            jTextFieldAkhirCetakFrame.setText("");
        }
    }//GEN-LAST:event_jCheckBoxCetakFrameMouseClicked

    private void jTextFieldNamaBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNamaBarangMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaBarangMouseEntered
    public void tampilanAwal() {
//        jTextFieldKodeKategori.setText("Masukkan Kode Kategori");
////        teks_kode_kategori.setMaximumSize(teks_kode_kategori.getPreferredSize());
        jLabelErrorBeliSebelum.setText("");
        jLabelErrorBeliSetelah.setText("");
        jLabelErrorKodeBarang.setText("");
        jLabelErrorNamaBarang.setText("");
        jLabelErrorQtyMax.setText("");
        jLabelErrorQtyMin.setText("");
        jLabelErrorRitelSebelum.setText("");
        jLabelErrorRitelSetelah.setText("");

        jTextFieldBeliSebelum.setText("0");
        jTextFieldBeliSetelah.setText("0");
//        jTextFieldKodeBarang.setEnabled(true);
        jTextFieldKodeBarang.setText("0");
        jTextFieldNamaBarang.setText("Masukkan Nama Barang");
        jTextFieldQtyMax.setText("0");
        jTextFieldQtyMin.setText("0");
        jTextFieldRitelSebelum.setText("0");
        jTextFieldRitelSetelah.setText("0");
        //        jTextFieldKodeKategori.setPreferredSize(jTextFieldKodeKategori.getPreferredSize());
        jTextFieldBeliSebelum.setPreferredSize(jTextFieldBeliSebelum.getPreferredSize());
        jTextFieldBeliSetelah.setPreferredSize(jTextFieldBeliSetelah.getPreferredSize());
        jTextFieldKodeBarang.setPreferredSize(jTextFieldKodeBarang.getPreferredSize());
        jTextFieldKodeBarang.setPreferredSize(jTextFieldKodeBarang.getPreferredSize());
        jTextFieldNamaBarang.setPreferredSize(jTextFieldNamaBarang.getPreferredSize());
        jTextFieldQtyMax.setPreferredSize(jTextFieldQtyMax.getPreferredSize());
        jTextFieldQtyMin.setPreferredSize(jTextFieldQtyMin.getPreferredSize());
        jTextFieldRitelSebelum.setPreferredSize(jTextFieldRitelSebelum.getPreferredSize());
        jTextFieldRitelSetelah.setPreferredSize(jTextFieldRitelSetelah.getPreferredSize());
        //        jTextFieldKodeKategori.setForeground(Color.LIGHT_GRAY);
        jTextFieldBeliSebelum.setForeground(Color.LIGHT_GRAY);
        jTextFieldBeliSetelah.setForeground(Color.LIGHT_GRAY);
        jTextFieldKodeBarang.setForeground(Color.LIGHT_GRAY);
        jTextFieldKodeBarang.setForeground(Color.LIGHT_GRAY);
        jTextFieldNamaBarang.setForeground(Color.LIGHT_GRAY);
        jTextFieldQtyMax.setForeground(Color.LIGHT_GRAY);
        jTextFieldQtyMin.setForeground(Color.LIGHT_GRAY);
        jTextFieldRitelSebelum.setForeground(Color.LIGHT_GRAY);
        jTextFieldRitelSetelah.setForeground(Color.LIGHT_GRAY);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftarmenuArsip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftarmenuArsip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftarmenuArsip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftarmenuArsip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new daftarmenuArsip().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonCekDaftarMenu;
    private javax.swing.JButton jButtonCetakFrameCetak;
    private javax.swing.JButton jButtonCetakFrameKeluar;
    private javax.swing.JButton jButtonCetakFrameTampil;
    private javax.swing.JButton jButtonInternalFrameKeluar;
    private javax.swing.JButton jButtonJInternalFrameCari;
    private javax.swing.JButton jButtonJInternalFrameHapus;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JButton jButtonList;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonUpload;
    private javax.swing.JCheckBox jCheckBoxCetakFrame;
    private javax.swing.JComboBox jComboBoxKategoriBarang;
    private javax.swing.JComboBox jComboBoxSatuan;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrameCetakBarang;
    private javax.swing.JInternalFrame jInternalFrameListBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelErrorBeliSebelum;
    private javax.swing.JLabel jLabelErrorBeliSetelah;
    private javax.swing.JLabel jLabelErrorKodeBarang;
    private javax.swing.JLabel jLabelErrorNamaBarang;
    private javax.swing.JLabel jLabelErrorQtyMax;
    private javax.swing.JLabel jLabelErrorQtyMin;
    private javax.swing.JLabel jLabelErrorRitelSebelum;
    private javax.swing.JLabel jLabelErrorRitelSetelah;
    private javax.swing.JLabel jLabelGambar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableJInternalFrame;
    private javax.swing.JTable jTableJInternalFrameCetakBarang;
    private javax.swing.JTextField jTextFieldAkhirCetakFrame;
    private javax.swing.JTextField jTextFieldAwalCetakFrame;
    private javax.swing.JTextField jTextFieldBeliSebelum;
    private javax.swing.JTextField jTextFieldBeliSetelah;
    private javax.swing.JTextField jTextFieldJInternalFrame;
    private javax.swing.JTextField jTextFieldKodeBarang;
    private javax.swing.JTextField jTextFieldNamaBarang;
    private javax.swing.JTextField jTextFieldQtyMax;
    private javax.swing.JTextField jTextFieldQtyMin;
    private javax.swing.JTextField jTextFieldRitelSebelum;
    private javax.swing.JTextField jTextFieldRitelSetelah;
    // End of variables declaration//GEN-END:variables
}
